# Generated by Django 4.2 on 2023-04-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='dueno',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='reunionusuario',
            old_name='reunion',
            new_name='reunion_id',
        ),
        migrations.RenameField(
            model_name='reunionusuario',
            old_name='usuario',
            new_name='user_id',
        ),
    ]
