# Generated by Django 4.2 on 2023-04-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiepractico2web3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='nombreReunion',
            new_name='nombre_reunion',
        ),
    ]
