# Generated by Django 4.2 on 2023-05-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiepractico3web3django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='apiepractico3web3django.genero')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego', to='apiepractico3web3django.juego')),
            ],
        ),
    ]
