# Generated by Django 4.2 on 2023-06-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipractico4web3django', '0003_respuestaencuesta_respuestapregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcionpregunta',
            old_name='pregunta',
            new_name='pregunta_id',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='encuesta',
            new_name='encuesta_id',
        ),
    ]
