# Generated by Django 4.2 on 2023-06-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipractico4web3django', '0004_rename_pregunta_opcionpregunta_pregunta_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcionpregunta',
            old_name='pregunta_id',
            new_name='pregunta',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='encuesta_id',
            new_name='encuesta',
        ),
    ]
