# Generated by Django 4.2 on 2023-06-07 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apipractico4web3django', '0005_rename_pregunta_id_opcionpregunta_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_en_pregunta', to='apipractico4web3django.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_en_encuesta', to='apipractico4web3django.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_usuario', to='apipractico4web3django.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_encuesta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_de_preagunta_en_resolucion_de_encuesta', to='apipractico4web3django.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='respuesta_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_en_resolucion_de_encuesta', to='apipractico4web3django.respuestaencuesta'),
        ),
        migrations.AlterField(
            model_name='usuarioencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='apipractico4web3django.encuesta'),
        ),
        migrations.AlterField(
            model_name='usuarioencuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
